---
- host: all
  become: true
  tasks:
    - name: Install python pip
     yum:
       name:python-pip
       state: present
   - name: Install docker-py python module
     pip:
       name: docker-py
       state: present     
   - name: Run the docker container
     docker container:
       name:
       image: abdulbabawale/todobackend:1.0.3 
       state: started
       published_ports:
       -0.0.0.0:5000:5000
