---
- host: all
  become: true
  tasks:
    - name: Install python pip
     yum:
       name:python-pip
       state: present
       
   - name: Install docker and docker compose
     apt:
       name:"{{ item }}"
       state: present
     loop:
       - docker.io
       - docker-compose 
       
   - name: Install docker-py python module
     pip:
       name: docker-py
       state: present 

   - name: start docker
     service:
       name: docker
       state: started
       enabled: yes 
       
   - name: pull the latest docker image
     docker image:
       name: abdulbabawale/todobackend:1.0.3 
       source: pull
       state: present
       
   - name: Run the docker container
     docker container:
       name:
       image: abdulbabawale/todobackend:1.0.3 
       state: started
       published_ports:
       -0.0.0.0:5000:5000
