---
- host: all
  become: true
  tasks:
    - name: Install python pip
     yum:
       name:python-pip
       state: present
   - name: Install docker-py python module
     pip:
       name: docker-py
       state: present 
   - name: Run the docker container
     command: docker run -p 8000:8000  abdulbabawale/todobackend:1.0.3 
    
