---
- hosts: inventory
  become: true
  tasks:
       
   - name: Install Python 2.7 and pip
      dnf:
        name:
          - python2
          - python2-pip
        state: present

    - name: Set alternatives for Python 2.7
      command: alternatives --set python /usr/bin/python2.7

    - name: Verify Python version
      command: python --version
      register: python_version
      changed_when: false

    - name: Install virtualenv for Python 2.7
      pip:
        name: virtualenv
        executable: pip2.7
        state: present

    - name: Create a virtual environment for Python 2.7
      command: virtualenv -p python2.7 /path/to/your/virtualenv 

   - name: Install docker 
     become: true
     become_user: root
     package:
       name: 
         - docker
       state: present 

   - name: Install pip
     become: true
     become_user: root
     package:
       name: 
         - pip
       state: present     
       
   - name: Install docker-py python module
     become: true
     become_user: root
     pip:
       name: docker-py
       state: present 

   - name: start docker
     service:
       name: docker
       state: started
       enabled: yes 
       
   - name: pull the latest docker image
     docker_image:
       name: abdulbabawale/todobackend:1.0.3 
       source: pull
       state: present
       
   - name: Run the docker container
     docker_container:
       name:
       image: abdulbabawale/todobackend:1.0.3 
       state: started
       published_ports:
         - "0.0.0.0:5000:5000"
